apiVersion: v1
kind: Service
metadata:
  namespace: devsecops
  name: vulnerable-app
spec:
  selector:
    app: vulnerable-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
