apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vulnerable-app-ingress
spec:
  podSelector:
    matchLabels:
      app: vulnerable-app

  policyTypes:
    - Ingress

  ingress:
    - from:
        - podSelector:
            matchLabels:
              access: vulnerable-app
      ports:
        - protocol: TCP
          port: 5000
